### ISSUE TITLE
Didnt work on 5.1.9 on windows

### ISSUE THREAD

**Issue by imyaFamiliev** [sparkfunX/Buzzard#20]
Hello!
I tried to copy folder Buzzard-master from git ad its folder contents  to c:\Program Files\KiCad\share\kicad\scripting\plugins\ (there are other working well plugins), then refresh plugin list and reopen kicad
Nothing changes.
I dont see Buzzard plugin icon on pcbnew like on these tweet
https://twitter.com/i/status/1348957557503578113

**Comment by VedantParanjape** [comment]
Hi, this doesn't natively support kicad, check this fork of port for 5.99, it works on 5.1.9: https://github.com/VedantParanjape/KiBuzzard

credits: https://github.com/gregdavill/KiBuzzard
